### ISSUE TITLE
Something went wrong on itch-setup

### ISSUE THREAD

**Issue by ejkun** [itchio/itch-setup#11]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 08:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:253
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by fasterthanlime** [comment]
That issue was fixed (server-side) a few days ago, it should work for you now.
