### ISSUE TITLE
Duplicate translations in Portuguese PT and BR

### ISSUE THREAD

**Issue by bugcrazy** [itchio/itch-setup#12]
Duplicate translations pt-PT.json and pt-BR.json are old translations, the new ones are pt_PT.json and pt-BR.json, all in the locales folder. https://github.com/itchio/itch-setup/tree/master/data/locales

This error message appears when you define languages in Portuguese pt and br in the app "No such locale /home/bcrazy/.itch/app-25.4.0/resources/app.asar/src/static/locales/pt.json"
The app tries to download pt.json, that there is no link https://locales.itch.ovh/itch/pt-PT.json and the same occurs with pt-PT and pt-BR, there are only links to https://locales.itch.ovh/itch/pt_PT.json and https://locales.itch.ovh/itch/pt_BR.json

**Comment by fasterthanlime** [comment]
Closed in https://github.com/itchio/itch-setup/commit/4b0786e9d85e08ddafce90a138695c3b5c48295a

**Comment by fasterthanlime** [comment]
It appears your main issue is with the itch app (ie. https://github.com/itchio/itch/issues/2451), so I don't think a new release of itch-setup is needed for now? The commit I just made is basically a cleanup, I don't think it should affect you.

Or did you experience problems while installing the itch app itself?

**Comment by bugcrazy** [comment]
There was no change in the pt and br language selection, they remain untranslated in the app, there was only an improvement in the "system language" selection.

I had no problems installing the app, only translation and these now:

butlerd/make-client "(butlerd) no handler for notification Log (in Game.FindUploads convo)"

Messages appear in mcall and m/reac/down/driver as the same content below!

"Caught butler error:"
"JavaScript stack: Error: JSON-RPC conversation cancelled
at Conversation.cancel (/home/bcrazy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:21649:24)    at Conversation.close (/home/bcrazy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:21657:14)
at Socket.sock.on (/home/bcrazy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:21441:22)
at emitOne (events.js:116:13)  at Socket.emit (events.js:211:7)   at TCP._handle.close [as _onclose] (net.js:554:12)"

**Comment by fasterthanlime** [comment]
> "Caught butler error:"
> "JavaScript stack: Error: JSON-RPC conversation cancelled
> at Conversation.cancel (/home/bcrazy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:21649:24) at Conversation.close (/home/bcrazy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:21657:14)
> at Socket.sock.on (/home/bcrazy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:21441:22)
> at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at TCP._handle.close [as _onclose] (net.js:554:12)"

This is an expected error, also has nothing to do with locales.

I'm also seeing problems when selecting `pt_PT` and `pt_BR` in the language switcher on itch v25.4.0 at the moment (I'm seeing the name of the translation strings rather than their brazilian version).

Unfortunately there's not much more I can do at this point except work on shipping the next version, I recommend you stick with English for now, sorry for the trouble :(.
