### ISSUE TITLE
Missing libwinpthread-1.dll on Windows

### ISSUE THREAD

**Issue by jbit** [itchio/itch-setup#13]
Hi,

As reported on the forums, the Windows installer does not start right now due to a DLL dependency error: https://itch.io/t/840497/cant-install-app-due-to-missing-dll-file

Reproduction steps:
  - Download the installer from: https://itch.io/app
  - (This gives itch-setup.exe with md5sum of 7850a1a24304c3e63738ff959877e30e )
  - Run on Windows 10.0.18363.900
  - Following dialog appears:
![The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this problem.](https://img.itch.zone/aW1nLzM3MDEzNzcucG5n/original/7XLWZF.png)

Dependency Walker shows the dependency:
![Dependency Walker screenshot](https://img.itch.zone/aW1nLzM3MDEzOTgucG5n/original/1vCuIJ.png)

`libwinpthread-1.dll` is a mingw32 library and so the error might not occur on developer machines since mingw32 might be in the search path. Having a quick google, it looks like other golang projects have had similar issues, e.g.:

https://github.com/go-vgo/robotgo/issues/235

A possible fix seems to be adding `-extldflags "-static"`  to the go ldflags... Presumably that'd be https://github.com/itchio/itch-setup/blob/a6d15a6c339974981c103b35952c6b4d961f8034/release/build.js#L190

Let me know if I can provide any other information

--jbit

**Comment by fasterthanlime** [comment]
Thanks for reporting it here - I don't keep track well enough of what's going on in the itch forums.

That's a very familiar error, I'll look into it right now. I'm not seeing the dependency for the x86_64 builds though, maybe it's only for i686.

**Comment by fasterthanlime** [comment]
Yeah confirmed, the dependency is only there for the 32-bit build:

![image](https://user-images.githubusercontent.com/7998310/85199191-e2c86a80-b2ed-11ea-9ce4-d8019268612c.png)

And https://itch.io/app serves a 64-bit installer to most users, so that's why I haven't been drowning in reports of this for the past N days.

**Comment by fasterthanlime** [comment]
itch-setup v1.23.0 has been released and is being served on https://itch.io/app now.

**Comment by jbit** [comment]
> itch-setup v1.23.0 has been released and is being served on https://itch.io/app now.
Sweet, I just grabbed it and it works now. Confirmed fixed! Thanks :)

For what it's worth, I'm on 64bit Windows, but the https://itchi.io/app site was serving me the i686 installer.

**Comment by fasterthanlime** [comment]
Yeah, I was wondering what browser you used / what your User Agent string looked like!

**Comment by jbit** [comment]
I use Firefox, user-agent is: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
