### ISSUE TITLE
Silent installation does not work, it installs non-silently.

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch-setup#2]
```
$ ./itch-setup --help
usage: itch-setup [<flags>] [<args>...]

The itch installer and self-updater

Flags:
  -h, --help             Show context-sensitive help (also try --help-long and --help-man).
      --prefer-launch    Launch if a valid version of itch is installed
      --upgrade          Upgrade the itch app if necessary
      --uninstall        Uninstall the itch app
      --relaunch         Relaunch a new version of the itch app
      --relaunch-pid=RELAUNCH-PID  
                         PID to wait for before relaunching
      --appname=APPNAME  Application name (itch or kitch)
      --silent           Run installation silently
  -V, --version          Show application version.

Args:
  [<args>]  Arguments to pass down to itch (only supported on Linux & Windows)
```
But when I actually run `./itch-setup --silent`, it installs, non-silently, showing both installer and the installed Itch. I would like to have working silent installation functionality for [Linux-tools](https://github.com/aaronfranke/Linux-tools/blob/master/ubuntu-only/programs-to-install.sh).

Version info:

```
$ ./itch-setup --version
v1.12.0, built on Oct  9 2018 @ 06:19:03, ref f34425d2a0952ca593d92c50679619eb4da0ad87
```

**Comment by fasterthanlime** [comment]
Yeeep silent mode has been used in the past to:

  * Skip "pick a folder" on Windows when I was investigating a hard-to-reproduce bug when healing a folder (that's how itch-setup installs the app). On Windows it hides the window, so it's sorta silent.
  * Test the error state on macOS (it shows "silent mode not supported on macOS")

However I intend to make the silent mode work properly on Linux at some point.

A few notes on that:

  * It'll still need gtk3+ libraries on startup, that's unavoidable
    * It technically isn't unavoidable - but it would be impractical to move to a dlopen model right now, unless https://github.com/gotk3/gotk3 started supporting it (and with the current Go toolchain, I'm not holding my breath)
  * However, it shouldn't require an X display (or wayland server or whatever), so we can't just do the Windows trick where we create a window and then hide it
  * The proper way to implement is to have a "UI" interface somewhere in https://github.com/itchio/itch-setup/blob/master/native/native_linux.go that somehow works for both GTK (an asynchronous, callback-based thing) and the CLI (an immediate thing). That way both can still have the same "native bits" (how to launch, how to relaunch something, where are XDG files located, etc.)

It's probably not a lot of work, someone just needs to, y'know, do it. I can try for next week, but no guarantees!

**Comment by fasterthanlime** [comment]
Look at this cute thing:

![image](https://user-images.githubusercontent.com/7998310/53292497-7a35b000-37c3-11e9-985c-904da6de5225.png)
