### ISSUE TITLE
Install itch.app crash on macOS

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch-setup#3]
## Basic facts

itch-setup is a golang app. "Install itch.app" is a regular app bundle.

The app bundle is signed, and the DMGs are signed. `spctl` and `codesign` are both happy with it.

## "Install itch.app" findings:

  - Extracted .zip = fails on first open, succeeds on second
  - Mounted dmg = fails on open until you check "Don't ask me again for this volume" and open again
  - ditto'd from dmg = works on open
  
## xattrs

dmg xattr for `com.apple.quarantine`

```
0183;5bc99105;Safari;84A9D2E3-A14A-4E55-AFEE-4D0A79E3010B
```

The important part are the first four characters, which are flags: *0183*.

Setting this xattr value for `com.apple.quarantine` on `Install itch.app` reliably makes it:

  * Pop up a Gatekeeper dialog
  * Then pop up in the Dock, then crash
  
![image](https://user-images.githubusercontent.com/7998310/47209094-d1e48a80-d38f-11e8-8ede-ba14068f5527.png)

GIF capture:

![install-itch-crash](https://user-images.githubusercontent.com/7998310/47209219-17a15300-d390-11e8-99af-a64217372cc6.gif)

After cancelling open: `com.apple.quarantine` has flags *01a3*.
After confirming open, `com.apple.quarantine` has flags *01e3*.

## Working theory

The app is ran differently the first time when it has that xattr and you pick "Open" in the gatekeeper dialog.

  * It doesn't seem to matter that it's in `~/Downloads`, `~/Applications` or `/Applications`
  * what matters isthe xattr

When ran from the DMG;

  * The DMG file has the quarantine xattr
  * The app bundle inside the mounted volume does not have the quarantine xattr
  * Picking "Open" in the dialog makes itch-setup crash (the Launch Service Monitor duly notes that our app exited)
  * Picking "Don't ask again for apps in this volume" probably sets DMG's `com.apple.quarantine` xattr flags to *01e3*.

**Comment by gingerbeardman** [comment]
What happens if you open the DMG with [FastDMG](https://www.sveinbjorn.org/fastdmg)?

**Comment by fasterthanlime** [comment]
## Breakthrough

AS IT TURNS OUT, macOS passes an argument that looks like `-psn_0_3281697` when the app is launched in the conditions described above.

kingpin validates all arguments, and so it exits immediately:

![image](https://user-images.githubusercontent.com/7998310/47211538-ffcccd80-d395-11e8-93ed-c62b1fa0bf3a.png)

**Comment by gingerbeardman** [comment]
What the heck. Nice work tracking that down

**Comment by gingerbeardman** [comment]
https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder

**Comment by gingerbeardman** [comment]
Seems to be side effect of the app supporting pre-10.9 versions of Mac OS X?

**Comment by fasterthanlime** [comment]
Fixed in:

  * https://github.com/itchio/itch-setup/commit/3f1e9486fece37aededf696323e828498d579b2f
  * https://github.com/itchio/itch-setup/commit/f2239197ebbaf767f1c8c354666561b9010668ee

Thanks for tuning in @gingerbeardman !

**Comment by fasterthanlime** [comment]
> Seems to be side effect of the app supporting pre-10.9 versions of Mac OS X?

Oh, do you think it wouldn't pass that argument if I specified, say, macOS 10.10 as the target in the `Info.plist` ? (I can't remember the exact name of the key, my mac-fu is rusty since my MBP went to mac heaven)

**Comment by gingerbeardman** [comment]
Yes, I think the argument would not be passed if you made that change.
