### ISSUE TITLE
Butler path not working

### ISSUE THREAD

**Issue by NangiDev** [itchio/itch-setup#6]
Following the instructions for setting up Butler to be in your path does not work.

https://itch.io/docs/butler/installing.html

On Linux this:
export PATH="$PATH:$HOME/.config/itch/apps/butler"
had to be changed to:
export PATH="$PATH:$HOME/.config/itch/broth/butler/versions/15.12.0"

Then it worked but will break if updated version.

Had the same problem on windows10

**Comment by fasterthanlime** [comment]
I see you skipped over the first section of that page ;)

`$HOME/.config/itch/apps/butler` only exists if you install https://fasterthanlime.itch.io/butler with the app (that's the default install location on Linux).

It is *not* recommended to use the version in `broth/` - as you noted, this will break then itch updates its own dependencies, it's not a stable path.

I agree that it's an easy mistake to make, the docs page could be restructured to be clearer - and maybe a section could be added about avoiding the `broth/` folder, the app's dependencies are better left alone.
